//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACLRule) DeepCopyInto(out *ACLRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACLRule.
func (in *ACLRule) DeepCopy() *ACLRule {
	if in == nil {
		return nil
	}
	out := new(ACLRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessList) DeepCopyInto(out *AccessList) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ACLRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessList.
func (in *AccessList) DeepCopy() *AccessList {
	if in == nil {
		return nil
	}
	out := new(AccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationRef) DeepCopyInto(out *AllocationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationRef.
func (in *AllocationRef) DeepCopy() *AllocationRef {
	if in == nil {
		return nil
	}
	out := new(AllocationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomain) DeepCopyInto(out *BridgeDomain) {
	*out = *in
	if in.EVPN != nil {
		in, out := &in.EVPN, &out.EVPN
		*out = new(EVPNSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IRB != nil {
		in, out := &in.IRB, &out.IRB
		*out = new(IRBSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomain.
func (in *BridgeDomain) DeepCopy() *BridgeDomain {
	if in == nil {
		return nil
	}
	out := new(BridgeDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimRef) DeepCopyInto(out *ClaimRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimRef.
func (in *ClaimRef) DeepCopy() *ClaimRef {
	if in == nil {
		return nil
	}
	out := new(ClaimRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EVPNSpec) DeepCopyInto(out *EVPNSpec) {
	*out = *in
	if in.RouteTargets != nil {
		in, out := &in.RouteTargets, &out.RouteTargets
		*out = new(RouteTargets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EVPNSpec.
func (in *EVPNSpec) DeepCopy() *EVPNSpec {
	if in == nil {
		return nil
	}
	out := new(EVPNSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fabric) DeepCopyInto(out *Fabric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fabric.
func (in *Fabric) DeepCopy() *Fabric {
	if in == nil {
		return nil
	}
	out := new(Fabric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Fabric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricList) DeepCopyInto(out *FabricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Fabric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricList.
func (in *FabricList) DeepCopy() *FabricList {
	if in == nil {
		return nil
	}
	out := new(FabricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNode) DeepCopyInto(out *FabricNode) {
	*out = *in
	if in.ASN != nil {
		in, out := &in.ASN, &out.ASN
		*out = new(int64)
		**out = **in
	}
	if in.RouteReflector != nil {
		in, out := &in.RouteReflector, &out.RouteReflector
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNode.
func (in *FabricNode) DeepCopy() *FabricNode {
	if in == nil {
		return nil
	}
	out := new(FabricNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSpec) DeepCopyInto(out *FabricSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]FabricNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Underlay.DeepCopyInto(&out.Underlay)
	in.Overlay.DeepCopyInto(&out.Overlay)
	out.MTU = in.MTU
	if in.Inventory != nil {
		in, out := &in.Inventory, &out.Inventory
		*out = make([]InventoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = make([]MaintenanceEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSpec.
func (in *FabricSpec) DeepCopy() *FabricSpec {
	if in == nil {
		return nil
	}
	out := new(FabricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricStatus) DeepCopyInto(out *FabricStatus) {
	*out = *in
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]AllocationRef, len(*in))
		copy(*out, *in)
	}
	if in.RenderedConfigs != nil {
		in, out := &in.RenderedConfigs, &out.RenderedConfigs
		*out = make([]RenderedConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricStatus.
func (in *FabricStatus) DeepCopy() *FabricStatus {
	if in == nil {
		return nil
	}
	out := new(FabricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	out.Service = in.Service
	if in.Identifiers != nil {
		in, out := &in.Identifiers, &out.Identifiers
		*out = make([]ReleasedIdentifier, len(*in))
		copy(*out, *in)
	}
	if in.DeviceObjects != nil {
		in, out := &in.DeviceObjects, &out.DeviceObjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.RecordedAt.DeepCopyInto(&out.RecordedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRBSpec) DeepCopyInto(out *IRBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRBSpec.
func (in *IRBSpec) DeepCopy() *IRBSpec {
	if in == nil {
		return nil
	}
	out := new(IRBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierClaim) DeepCopyInto(out *IdentifierClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierClaim.
func (in *IdentifierClaim) DeepCopy() *IdentifierClaim {
	if in == nil {
		return nil
	}
	out := new(IdentifierClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentifierClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierClaimList) DeepCopyInto(out *IdentifierClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentifierClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierClaimList.
func (in *IdentifierClaimList) DeepCopy() *IdentifierClaimList {
	if in == nil {
		return nil
	}
	out := new(IdentifierClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentifierClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierClaimSpec) DeepCopyInto(out *IdentifierClaimSpec) {
	*out = *in
	out.PoolRef = in.PoolRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierClaimSpec.
func (in *IdentifierClaimSpec) DeepCopy() *IdentifierClaimSpec {
	if in == nil {
		return nil
	}
	out := new(IdentifierClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierClaimStatus) DeepCopyInto(out *IdentifierClaimStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierClaimStatus.
func (in *IdentifierClaimStatus) DeepCopy() *IdentifierClaimStatus {
	if in == nil {
		return nil
	}
	out := new(IdentifierClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierPool) DeepCopyInto(out *IdentifierPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierPool.
func (in *IdentifierPool) DeepCopy() *IdentifierPool {
	if in == nil {
		return nil
	}
	out := new(IdentifierPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentifierPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierPoolList) DeepCopyInto(out *IdentifierPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentifierPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierPoolList.
func (in *IdentifierPoolList) DeepCopy() *IdentifierPoolList {
	if in == nil {
		return nil
	}
	out := new(IdentifierPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentifierPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierPoolRef) DeepCopyInto(out *IdentifierPoolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierPoolRef.
func (in *IdentifierPoolRef) DeepCopy() *IdentifierPoolRef {
	if in == nil {
		return nil
	}
	out := new(IdentifierPoolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierPoolSpec) DeepCopyInto(out *IdentifierPoolSpec) {
	*out = *in
	if in.Range != nil {
		in, out := &in.Range, &out.Range
		*out = new(IdentifierRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierPoolSpec.
func (in *IdentifierPoolSpec) DeepCopy() *IdentifierPoolSpec {
	if in == nil {
		return nil
	}
	out := new(IdentifierPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierPoolStatus) DeepCopyInto(out *IdentifierPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierPoolStatus.
func (in *IdentifierPoolStatus) DeepCopy() *IdentifierPoolStatus {
	if in == nil {
		return nil
	}
	out := new(IdentifierPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentifierRange) DeepCopyInto(out *IdentifierRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentifierRange.
func (in *IdentifierRange) DeepCopy() *IdentifierRange {
	if in == nil {
		return nil
	}
	out := new(IdentifierRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryEntry) DeepCopyInto(out *InventoryEntry) {
	*out = *in
	if in.AccessPorts != nil {
		in, out := &in.AccessPorts, &out.AccessPorts
		*out = make([]PortName, len(*in))
		copy(*out, *in)
	}
	if in.UntaggedAccessPorts != nil {
		in, out := &in.UntaggedAccessPorts, &out.UntaggedAccessPorts
		*out = make([]PortName, len(*in))
		copy(*out, *in)
	}
	if in.FabricPorts != nil {
		in, out := &in.FabricPorts, &out.FabricPorts
		*out = make([]PortName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryEntry.
func (in *InventoryEntry) DeepCopy() *InventoryEntry {
	if in == nil {
		return nil
	}
	out := new(InventoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTUSpec) DeepCopyInto(out *MTUSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTUSpec.
func (in *MTUSpec) DeepCopy() *MTUSpec {
	if in == nil {
		return nil
	}
	out := new(MTUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceEntry) DeepCopyInto(out *MaintenanceEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceEntry.
func (in *MaintenanceEntry) DeepCopy() *MaintenanceEntry {
	if in == nil {
		return nil
	}
	out := new(MaintenanceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Network) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkAttachment) DeepCopyInto(out *NetworkAttachment) {
	*out = *in
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(AttachmentVLAN)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachment.
func (in *NetworkAttachment) DeepCopy() *NetworkAttachment {
	if in == nil {
		return nil
	}
	out := new(NetworkAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkList) DeepCopyInto(out *NetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Network, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkList.
func (in *NetworkList) DeepCopy() *NetworkList {
	if in == nil {
		return nil
	}
	out := new(NetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRouter) DeepCopyInto(out *NetworkRouter) {
	*out = *in
	if in.RouteTargets != nil {
		in, out := &in.RouteTargets, &out.RouteTargets
		*out = new(RouteTargets)
		(*in).DeepCopyInto(*out)
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]IPPrefix, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRouter.
func (in *NetworkRouter) DeepCopy() *NetworkRouter {
	if in == nil {
		return nil
	}
	out := new(NetworkRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.VLANs != nil {
		in, out := &in.VLANs, &out.VLANs
		*out = make([]NetworkVLAN, len(*in))
		copy(*out, *in)
	}
	if in.BridgeDomains != nil {
		in, out := &in.BridgeDomains, &out.BridgeDomains
		*out = make([]BridgeDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Routers != nil {
		in, out := &in.Routers, &out.Routers
		*out = make([]NetworkRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AccessLists != nil {
		in, out := &in.AccessLists, &out.AccessLists
		*out = make([]AccessList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]NetworkAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClaimRefs != nil {
		in, out := &in.ClaimRefs, &out.ClaimRefs
		*out = make([]ClaimRef, len(*in))
		copy(*out, *in)
	}
	if in.RenderedConfigs != nil {
		in, out := &in.RenderedConfigs, &out.RenderedConfigs
		*out = make([]RenderedConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVLAN) DeepCopyInto(out *NetworkVLAN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVLAN.
func (in *NetworkVLAN) DeepCopy() *NetworkVLAN {
	if in == nil {
		return nil
	}
	out := new(NetworkVLAN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlaySpec) DeepCopyInto(out *OverlaySpec) {
	*out = *in
	if in.RouteReflectors != nil {
		in, out := &in.RouteReflectors, &out.RouteReflectors
		*out = make([]DNSLabel, len(*in))
		copy(*out, *in)
	}
	if in.InterASVPN != nil {
		in, out := &in.InterASVPN, &out.InterASVPN
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlaySpec.
func (in *OverlaySpec) DeepCopy() *OverlaySpec {
	if in == nil {
		return nil
	}
	out := new(OverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolRef) DeepCopyInto(out *PoolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolRef.
func (in *PoolRef) DeepCopy() *PoolRef {
	if in == nil {
		return nil
	}
	out := new(PoolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleasedIdentifier) DeepCopyInto(out *ReleasedIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleasedIdentifier.
func (in *ReleasedIdentifier) DeepCopy() *ReleasedIdentifier {
	if in == nil {
		return nil
	}
	out := new(ReleasedIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedConfig) DeepCopyInto(out *RenderedConfig) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedConfig.
func (in *RenderedConfig) DeepCopy() *RenderedConfig {
	if in == nil {
		return nil
	}
	out := new(RenderedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteTargets) DeepCopyInto(out *RouteTargets) {
	*out = *in
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = make([]RouteTarget, len(*in))
		copy(*out, *in)
	}
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = make([]RouteTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteTargets.
func (in *RouteTargets) DeepCopy() *RouteTargets {
	if in == nil {
		return nil
	}
	out := new(RouteTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRef) DeepCopyInto(out *ServiceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRef.
func (in *ServiceRef) DeepCopy() *ServiceRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnderlaySpec) DeepCopyInto(out *UnderlaySpec) {
	*out = *in
	if in.AddressFamilies != nil {
		in, out := &in.AddressFamilies, &out.AddressFamilies
		*out = make([]AddressFamily, len(*in))
		copy(*out, *in)
	}
	if in.LoopbackPoolRef != nil {
		in, out := &in.LoopbackPoolRef, &out.LoopbackPoolRef
		*out = new(PoolRef)
		**out = **in
	}
	if in.LinkPoolRef != nil {
		in, out := &in.LinkPoolRef, &out.LinkPoolRef
		*out = new(PoolRef)
		**out = **in
	}
	if in.ASNPoolRef != nil {
		in, out := &in.ASNPoolRef, &out.ASNPoolRef
		*out = new(PoolRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnderlaySpec.
func (in *UnderlaySpec) DeepCopy() *UnderlaySpec {
	if in == nil {
		return nil
	}
	out := new(UnderlaySpec)
	in.DeepCopyInto(out)
	return out
}
