#!/usr/bin/env bash
# The first-party allocation authority's seed pools (T179; FR-104, FR-012, AD-33, AD-10;
# contracts/kuid-claim-profiles.md §1, §7). Offline; python3 + PyYAML.
#   the committed deploy/allocation/pools/{ipam,as,vlan,vni}.yaml are the generation of
#     `scripts/lib/inventory.sh --pools` from deploy/kuid/indices — byte for byte
#   generation is deterministic, names its input and the input's sha256, and carries no timestamp
#   every pool has the name of a kuid index and EXACTLY its range / prefix (read independently of
#     the generator): fabric01-loopback 10.0.0.0/24, fabric01-p2p 10.1.0.0/24, fabric01-underlay
#     65100–65199, fabric01-vlan 1000–4000, fabric01-vni 10000–20000; one pool per index, none more
#   the naming band 100–999 is outside every vlan pool (AD-33)
#   every pool is fabric.agentic-netops.io/v1alpha1 IdentifierPool in agentic-netops-allocation —
#     nothing in a *.kuid.dev group (FR-098)
#   deploy/allocation/pools/kustomization.yaml lists exactly the four files
#   negative controls: a changed kuid index range makes the committed pools no longer the
#     generation (the drift is caught); an IPIndex with two prefixes is refused, nothing written
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
# shellcheck source=../../../scripts/lib/inventory.sh
source "$ROOT/scripts/lib/inventory.sh"

fails=0
pass() { printf 'PASS %s\n' "$1"; }
fail() { printf 'FAIL %s\n' "$1"; fails=$((fails + 1)); [[ -n "${2:-}" ]] && printf '%s\n' "$2" | sed 's/^/    /'; }

IDX="$ROOT/deploy/kuid/indices"
POOLS="$ROOT/deploy/allocation/pools"

# ------------------------------------------------------------------ committed == generation
if inventory::generate_pools "$IDX" "$TMP/gen" 2>"$TMP/err"; then
  d=""
  for f in ipam as vlan vni; do
    diff -u "$POOLS/$f.yaml" "$TMP/gen/$f.yaml" >>"$TMP/diff" 2>&1 || d+=" $f.yaml"
  done
  if [[ -z "$d" ]]; then
    pass "deploy/allocation/pools/{ipam,as,vlan,vni}.yaml are the generation of inventory.sh --pools from deploy/kuid/indices"
  else
    fail "committed pools differ from the generation:${d} — re-run scripts/lib/inventory.sh --pools" "$(head -40 "$TMP/diff")"
  fi
else
  fail "inventory::generate_pools on the committed indices" "$(cat "$TMP/err")"
fi

inventory::generate_pools "$IDX" "$TMP/gen2" 2>/dev/null
if diff -r "$TMP/gen" "$TMP/gen2" >/dev/null 2>&1; then
  pass "generation is deterministic (two runs, identical bytes)"
else
  fail "generation is not deterministic"
fi
hdr_ok=true
for f in ipam as vlan vni; do
  src="$f"; [[ "$f" == vni ]] && src=genid
  sum="$(sha256sum "$IDX/$src.yaml" | cut -d' ' -f1)"
  grep -q "^# GENERATED by scripts/lib/inventory.sh --pools from deploy/kuid/indices/$src.yaml (sha256:$sum)" "$POOLS/$f.yaml" || { hdr_ok=false; echo "    $f.yaml: header does not name deploy/kuid/indices/$src.yaml sha256:$sum"; }
  grep -qE '[0-9]{4}-[0-9]{2}-[0-9]{2}(T| )[0-9]{2}:[0-9]{2}' "$POOLS/$f.yaml" && { hdr_ok=false; echo "    $f.yaml carries a timestamp"; }
done
[[ "$hdr_ok" == true ]] && pass "each pool file's header names its kuid index input and that input's sha256; no timestamp" \
  || fail "pool file headers"

# ------------------------------------------------------------------ ranges equal the kuid indices
if out="$(python3 - "$IDX" "$POOLS" <<'PY' 2>&1
import ipaddress, os, sys, yaml
idx_dir, pools_dir = sys.argv[1:3]
def load(p):
    return [d for d in yaml.safe_load_all(open(p)) if d]
kuid = {}
for f in ("ipam.yaml", "as.yaml", "vlan.yaml", "genid.yaml"):
    for d in load(os.path.join(idx_dir, f)):
        s = d["spec"]
        if d["kind"] == "IPIndex":
            kuid[d["metadata"]["name"]] = ("ip", [p["prefix"] for p in s["prefixes"]])
        else:
            t = {"ASIndex": "asn", "VLANIndex": "vlan", "GENIDIndex": "vni"}[d["kind"]]
            kuid[d["metadata"]["name"]] = (t, (s["minID"], s["maxID"]))
pools = {}
for f in ("ipam.yaml", "as.yaml", "vlan.yaml", "vni.yaml"):
    for d in load(os.path.join(pools_dir, f)):
        assert d["apiVersion"] == "fabric.agentic-netops.io/v1alpha1", d["apiVersion"]
        assert d["kind"] == "IdentifierPool", d["kind"]
        assert d["metadata"]["namespace"] == "agentic-netops-allocation", d["metadata"]
        n = d["metadata"]["name"]
        assert n not in pools, f"pool {n} twice"
        s = d["spec"]
        pools[n] = (s["type"], [s["prefix"]]) if s["type"] == "ip" else (s["type"], (s["range"]["start"], s["range"]["end"]))
assert set(pools) == set(kuid), f"pool names {sorted(pools)} != kuid index names {sorted(kuid)}"
for n in sorted(kuid):
    assert pools[n] == kuid[n], f"{n}: pool {pools[n]} != kuid index {kuid[n]}"
want = {"fabric01-loopback": ("ip", ["10.0.0.0/24"]), "fabric01-p2p": ("ip", ["10.1.0.0/24"]),
        "fabric01-underlay": ("asn", (65100, 65199)), "fabric01-vlan": ("vlan", (1000, 4000)),
        "fabric01-vni": ("vni", (10000, 20000))}
assert pools == want, f"pools {pools} != the contract's {want}"
for n, (t, r) in pools.items():
    if t == "vlan":
        lo, hi = r
        assert hi < 100 or lo > 999, f"vlan pool {n} {lo}-{hi} overlaps the naming band 100-999 (AD-33)"
    if t == "ip":
        ipaddress.ip_network(r[0])
print(f"{len(pools)} pools, each exactly its kuid index: " + ", ".join(f"{n} {t} {r if t == 'ip' else '%d-%d' % r}" for n, (t, r) in sorted(pools.items())))
PY
)"; then
  pass "every pool range equals its kuid index (vlan 1000–4000, vni 10000–20000; naming band 100–999 outside every pool): $out"
else
  fail "pool ranges vs kuid indices" "$out"
fi

if grep -hE '^(apiVersion|kind):' "$POOLS"/*.yaml | grep -qE 'kuid\.dev|Index$'; then
  fail "a pool file declares an object in a *.kuid.dev group or an *Index kind"
else
  pass "no pool file declares a *.kuid.dev object or an *Index kind (FR-098)"
fi

res="$(yq -r '.resources | join(",")' "$POOLS/kustomization.yaml" 2>&1)"
if [[ "$res" == "ipam.yaml,as.yaml,vlan.yaml,vni.yaml" ]] && [[ "$(yq -r .namespace "$POOLS/kustomization.yaml")" == agentic-netops-allocation ]]; then
  pass "deploy/allocation/pools/kustomization.yaml lists exactly ipam, as, vlan, vni in agentic-netops-allocation"
else
  fail "deploy/allocation/pools/kustomization.yaml resources: $res"
fi

# ------------------------------------------------------------------ negative controls
cp -r "$IDX" "$TMP/idx-drift"
sed -i 's/^  maxID: 4000$/  maxID: 4001/' "$TMP/idx-drift/vlan.yaml"
inventory::generate_pools "$TMP/idx-drift" "$TMP/gen-drift" 2>/dev/null
if ! grep -q 'end: 4001' "$TMP/gen-drift/vlan.yaml" 2>/dev/null; then
  fail "negative control: a widened kuid VLANIndex (maxID 4001) should render vlan end 4001"
elif diff -q "$POOLS/vlan.yaml" "$TMP/gen-drift/vlan.yaml" >/dev/null 2>&1; then
  fail "negative control: a changed kuid index range should make the committed vlan pool stale"
else
  pass "negative control: a changed kuid index range (VLANIndex maxID 4001) no longer matches the committed pools — drift is caught"
fi

cp -r "$IDX" "$TMP/idx-bad"
yq -i '(select(.metadata.name == "fabric01-p2p") | .spec.prefixes) += [{"prefix": "10.2.0.0/24"}]' "$TMP/idx-bad/ipam.yaml"
mkdir -p "$TMP/gen-bad"
if inventory::generate_pools "$TMP/idx-bad" "$TMP/gen-bad" 2>"$TMP/err-bad"; then
  fail "negative control: an IPIndex with two prefixes should be refused"
elif grep -q 'fabric01-p2p must carry exactly one prefix' "$TMP/err-bad" && [[ -z "$(ls -A "$TMP/gen-bad")" ]]; then
  pass "negative control: an IPIndex with two prefixes is refused naming it; nothing is written"
else
  fail "negative control: two-prefix refusal" "$(cat "$TMP/err-bad"; ls "$TMP/gen-bad")"
fi

echo
if [[ "$fails" -eq 0 ]]; then echo "pools_test: all passed"; exit 0; fi
echo "pools_test: ${fails} failed"; exit 1
