package topologyview

import (
	"fmt"
	"os"
	"path/filepath"
)

// Output file names inside the generator's output directory (scripts/lib/observability.sh
// installs them as ConfigMaps).
const (
	FileTargets = "gnmic-targets.txt"
	FileSVG     = "topology.svg"
	FilePanel   = "topology-panel.yaml"
	FileRules   = "topology-rules.yaml"
	FileDigest  = "inventory-digest.txt"
)

// Options drive Generate.
type Options struct {
	Topology     string // the containerlab inventory clab-io-draw was run over
	MgmtCIDR     string
	DrawioDir    string // clab-io-draw's output: one *.drawio and one *.flow_panel.yaml
	OutDir       string
	GeneratorRef string // the pinned clab-io-draw image reference, recorded as provenance
}

// Generate parses the inventory once and writes every artefact from it, then holds them to the
// inventory with Parity; nothing is written unless they agree.
func Generate(o Options) error {
	raw, err := os.ReadFile(o.Topology)
	if err != nil {
		return err
	}
	inv, err := ParseInventory(raw)
	if err != nil {
		return err
	}
	drawioPath, err := one(o.DrawioDir, "*.drawio")
	if err != nil {
		return err
	}
	panelPath, err := one(o.DrawioDir, "*.flow_panel.yaml")
	if err != nil {
		return err
	}
	prov := fmt.Sprintf("generated by internal/topologyview (T131) from %s sha256:%s", filepath.Base(o.Topology), inv.Digest)
	if o.GeneratorRef != "" {
		prov += " with " + o.GeneratorRef
	}

	ts, err := Targets(inv, o.MgmtCIDR)
	if err != nil {
		return err
	}
	db, err := os.ReadFile(drawioPath)
	if err != nil {
		return err
	}
	d, err := ParseDrawio(db)
	if err != nil {
		return err
	}
	pb, err := os.ReadFile(panelPath)
	if err != nil {
		return err
	}
	panel, err := RewritePanel(pb, inv, prov)
	if err != nil {
		return err
	}
	a := Assets{
		Targets:  FormatTargets(ts),
		SVG:      RenderSVG(d.Canonical(inv), prov),
		Panel:    panel,
		Rules:    Rules(inv, prov),
		MgmtCIDR: o.MgmtCIDR,
	}
	if err := Parity(inv, a); err != nil {
		return fmt.Errorf("generated view does not match the inventory:\n%w", err)
	}
	if err := os.MkdirAll(o.OutDir, 0o755); err != nil {
		return err
	}
	files := map[string][]byte{
		FileTargets: a.Targets,
		FileSVG:     a.SVG,
		FilePanel:   a.Panel,
		FileRules:   a.Rules,
		FileDigest:  []byte(inv.Digest + "  " + filepath.Base(o.Topology) + "\n"),
	}
	for name, b := range files {
		if err := os.WriteFile(filepath.Join(o.OutDir, name), b, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func one(dir, pattern string) (string, error) {
	m, err := filepath.Glob(filepath.Join(dir, pattern))
	if err != nil {
		return "", err
	}
	if len(m) != 1 {
		return "", fmt.Errorf("%s: want exactly one %s from clab-io-draw, found %d", dir, pattern, len(m))
	}
	return m[0], nil
}
