//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingPolicy) DeepCopyInto(out *MappingPolicy) {
	*out = *in
	if in.AllowLimitedEquivalence != nil {
		in, out := &in.AllowLimitedEquivalence, &out.AllowLimitedEquivalence
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingPolicy.
func (in *MappingPolicy) DeepCopy() *MappingPolicy {
	if in == nil {
		return nil
	}
	out := new(MappingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationEndpoint) DeepCopyInto(out *MigrationEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationEndpoint.
func (in *MigrationEndpoint) DeepCopy() *MigrationEndpoint {
	if in == nil {
		return nil
	}
	out := new(MigrationEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationGateway) DeepCopyInto(out *MigrationGateway) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationGateway.
func (in *MigrationGateway) DeepCopy() *MigrationGateway {
	if in == nil {
		return nil
	}
	out := new(MigrationGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPlan) DeepCopyInto(out *MigrationPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPlan.
func (in *MigrationPlan) DeepCopy() *MigrationPlan {
	if in == nil {
		return nil
	}
	out := new(MigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPlanList) DeepCopyInto(out *MigrationPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MigrationPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPlanList.
func (in *MigrationPlanList) DeepCopy() *MigrationPlanList {
	if in == nil {
		return nil
	}
	out := new(MigrationPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPlanSpec) DeepCopyInto(out *MigrationPlanSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.TargetNetworkRef = in.TargetNetworkRef
	in.MappingPolicy.DeepCopyInto(&out.MappingPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPlanSpec.
func (in *MigrationPlanSpec) DeepCopy() *MigrationPlanSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPlanStatus) DeepCopyInto(out *MigrationPlanStatus) {
	*out = *in
	if in.UnsupportedFeatures != nil {
		in, out := &in.UnsupportedFeatures, &out.UnsupportedFeatures
		*out = make([]UnsupportedFeature, len(*in))
		copy(*out, *in)
	}
	if in.GeneratedNetworkRef != nil {
		in, out := &in.GeneratedNetworkRef, &out.GeneratedNetworkRef
		*out = new(NetworkReference)
		**out = **in
	}
	if in.ProvenanceRef != nil {
		in, out := &in.ProvenanceRef, &out.ProvenanceRef
		*out = new(ProvenanceReference)
		(*in).DeepCopyInto(*out)
	}
	if in.PerDevice != nil {
		in, out := &in.PerDevice, &out.PerDevice
		*out = make([]PerDeviceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPlanStatus.
func (in *MigrationPlanStatus) DeepCopy() *MigrationPlanStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSource) DeepCopyInto(out *MigrationSource) {
	*out = *in
	in.NormalizedIntent.DeepCopyInto(&out.NormalizedIntent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSource.
func (in *MigrationSource) DeepCopy() *MigrationSource {
	if in == nil {
		return nil
	}
	out := new(MigrationSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkReference) DeepCopyInto(out *NetworkReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkReference.
func (in *NetworkReference) DeepCopy() *NetworkReference {
	if in == nil {
		return nil
	}
	out := new(NetworkReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedIntent) DeepCopyInto(out *NormalizedIntent) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]MigrationEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]MigrationPrefix, len(*in))
		copy(*out, *in)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(MigrationGateway)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedIntent.
func (in *NormalizedIntent) DeepCopy() *NormalizedIntent {
	if in == nil {
		return nil
	}
	out := new(NormalizedIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerDeviceStatus) DeepCopyInto(out *PerDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerDeviceStatus.
func (in *PerDeviceStatus) DeepCopy() *PerDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(PerDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvenanceReference) DeepCopyInto(out *ProvenanceReference) {
	*out = *in
	out.Network = in.Network
	if in.AnnotationKeys != nil {
		in, out := &in.AnnotationKeys, &out.AnnotationKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvenanceReference.
func (in *ProvenanceReference) DeepCopy() *ProvenanceReference {
	if in == nil {
		return nil
	}
	out := new(ProvenanceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsupportedFeature) DeepCopyInto(out *UnsupportedFeature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsupportedFeature.
func (in *UnsupportedFeature) DeepCopy() *UnsupportedFeature {
	if in == nil {
		return nil
	}
	out := new(UnsupportedFeature)
	in.DeepCopyInto(out)
	return out
}
