#!/usr/bin/env bash
# onboarding.sh — the device-onboarding DiscoveryRule, rendered for a management address
# space (T036; FR-015, FR-008).
#
# The four SR Linux nodes sit at fixed host offsets of MGMT_CIDR (lab/topology.clab.yml):
#   spine01 .11   spine02 .12   leaf01 .21   leaf02 .22
# deploy/sdc/onboarding/discovery-rule.yaml is exactly `onboarding::render 172.25.25.0/24`
# (the default MGMT_CIDR); tests/unit/sdconboard checks the committed file still equals it.
# For any other address space scripts/lib/sdc_onboard.sh renders the rule into a temporary
# copy of the onboarding directory and applies that — the committed file is never rewritten
# at run time.
#
# The rule is static discovery: fixed addresses with host names (each becomes the Target's
# name), the default Schema (srl.nokia.sdcio.dev 25.7.1), no discoveryProfile — so nothing is
# probed — and one target profile: credentials Secret srl-credentials (created in
# agentic-netops-system by scripts/lib/lab_secrets.sh; the name is substituted by the onboarding
# kustomization), connection profile gnmi-tls-skipverify, sync profile gnmi-get-config.
# Targets and everything they use live in agentic-netops-system because config-server v0.0.58
# lists them in the Target's namespace (AD-82 decision 2026-09-21-target-namespace).
#
#   onboarding::hosts <mgmt_cidr>            prints "<name> <address>" per node (stable order)
#   onboarding::render <mgmt_cidr>           prints the DiscoveryRule manifest
#
# Usage (as a script): onboarding.sh render <mgmt_cidr>

[[ -n "${__AGENTIC_NETOPS_ONBOARDING_SH:-}" ]] && return 0
__AGENTIC_NETOPS_ONBOARDING_SH=1

ONBOARDING_DEFAULT_CIDR="172.25.25.0/24"
# name:offset — the fixed management host offsets of the fabric nodes.
ONBOARDING_NODES=(spine01:11 spine02:12 leaf01:21 leaf02:22)

onboarding::hosts() {
  local cidr="${1:?usage: onboarding::hosts <mgmt_cidr>}"
  python3 - "$cidr" "${ONBOARDING_NODES[@]}" <<'PY'
import ipaddress, sys
try:
    net = ipaddress.ip_network(sys.argv[1], strict=True)
except ValueError as e:
    sys.exit(f"onboarding: MGMT_CIDR '{sys.argv[1]}' is not a network address: {e}")
if net.version != 4:
    sys.exit(f"onboarding: MGMT_CIDR '{sys.argv[1]}' is not IPv4")
for spec in sys.argv[2:]:
    name, off = spec.split(":")
    off = int(off)
    if off >= net.num_addresses - 1:
        sys.exit(f"onboarding: MGMT_CIDR {net} is too small for {name} at host offset .{off}")
    print(name, net.network_address + off)
PY
}

onboarding::render() {
  local cidr="${1:?usage: onboarding::render <mgmt_cidr>}" hosts name addr
  hosts="$(onboarding::hosts "$cidr")" || return 1
  cat <<EOF
# provenance: source=first-party version=v0.1.0
# GENERATED by scripts/lib/onboarding.sh \`onboarding::render ${cidr}\` — do not edit by hand.
# Static discovery of the four fabric nodes (T036; FR-015): each address becomes one Target in
# agentic-netops-system (config.sdcio.dev/v1alpha1 at config-server v0.0.58), named by its
# hostName. No discoveryProfile, so nothing is probed; the default Schema is compatibility-set
# part 4. Targets and everything they use live in agentic-netops-system because config-server
# v0.0.58 lists them in the Target's namespace (AD-82 decision 2026-09-21-target-namespace).
apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: fabric01-nodes
  namespace: agentic-netops-system
spec:
  period: 1m
  concurrentScans: 2
  defaultSchema:
    provider: srl.nokia.sdcio.dev
    version: 25.7.1
  addresses:
EOF
  while read -r name addr; do
    printf '  - address: %s\n    hostName: %s\n' "$addr" "$name"
  done <<<"$hosts"
  cat <<'EOF'
  targetConnectionProfiles:
  # the Secret's NAME (never a credential); substituted from deploy/sdc/onboarding/kustomization.yaml
  - credentials: __SRL_CREDENTIALS_SECRET__
    connectionProfile: gnmi-tls-skipverify
    syncProfile: gnmi-get-config
  targetTemplate:
    labels:
      agentic-netops.io/fabric: fabric01
EOF
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  set -euo pipefail
  case "${1:-}" in
    render) onboarding::render "${2:-${MGMT_CIDR:-$ONBOARDING_DEFAULT_CIDR}}" ;;
    *) echo "usage: onboarding.sh render [<mgmt_cidr>]" >&2; exit 2 ;;
  esac
fi
