#!/usr/bin/env python3
"""Capture the README's four figures from the same live lab that produced the accepted take (T163;
contracts/readme-and-walkthrough.md §4), into docs/images/ under the predecessor's file names:

  lab-topology.png              the Physical topology dashboard (the Clos generated by clab-io-draw
                                from the containerlab inventory, native port names), live
  grafana-fabric-telemetry.png  the Fabric dashboard with live data
  agent-ui.png                  the operator console mid-run, logged in, the mapper's interpretation
                                shown before anything is allocated — the take's own frame
  agent-ui-outcome.png          the end of the same transaction — the take's own frame

Grafana is logged in through its HTTP API before any page is opened, so no login form (and no
credential) is ever on screen; the console frames come from a take recorded after its login.
Then every figure is checked: 1920x1080, not blank (check_framing.py), and OCR'd with tesseract —
neither the live operator password nor the Grafana administrator password may appear in any
figure, nor a credential-shaped string. The report is printed as JSON (run it under evidence_run).

Usage: capture_figures.py --take final
"""
from __future__ import annotations

import argparse
import base64
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

BASE = Path(__file__).resolve().parent
REPO = BASE.parents[1]
IMAGES = REPO / "docs" / "images"
SHOTS = BASE / "shots"
GRAFANA = "http://127.0.0.1:19300"
DASH = {"lab-topology.png": "agentic-netops-physical-topology",
        "grafana-fabric-telemetry.png": "agentic-netops-fabric"}
CRED = re.compile(r"(?i)password\s*[:=]\s*\S|authorization:\s*basic|://[^/\s:@]+:[^/\s@]+@")


def secret(ns: str, name: str, key: str) -> str:
    out = subprocess.run(["kubectl", "-n", ns, "get", "secret", name, "-o", f"jsonpath={{.data.{key}}}"],
                         capture_output=True, text=True, check=True).stdout
    return base64.b64decode(out).decode()


def ocr(p: Path) -> str:
    r = subprocess.run(["tesseract", str(p), "stdout"], capture_output=True, text=True)
    return r.stdout


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--take", default="final")
    args = ap.parse_args()
    IMAGES.mkdir(parents=True, exist_ok=True)
    report: dict = {"figures": {}, "ok": True}

    # the console frames: the take's own screenshots (logged in before recording)
    pick = {"agent-ui.png": sorted(SHOTS.glob(f"{args.take}-C-mapper-*.png")),
            "agent-ui-outcome.png": sorted(SHOTS.glob(f"{args.take}-C-outcome-*.png"))}
    for name, cands in pick.items():
        if not cands:
            report["figures"][name] = {"error": "no such frame in the take"}
            report["ok"] = False
            continue
        shutil.copyfile(cands[-1], IMAGES / name)
        report["figures"][name] = {"source": f"testautomation/video/shots/{cands[-1].name}"}

    # the Grafana figures, live
    gf_user = secret("monitoring", "grafana-admin", "admin-user")
    gf_pass = secret("monitoring", "grafana-admin", "admin-password")
    op_pass = secret("agentic-netops-agents", "operator-credentials", "password")
    pf = subprocess.Popen(["kubectl", "-n", "monitoring", "port-forward", "svc/grafana", "19300:3000"],
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(4)
        from playwright.sync_api import sync_playwright
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            ctx = browser.new_context(viewport={"width": 1920, "height": 1080})
            r = ctx.request.post(f"{GRAFANA}/login", data={"user": gf_user, "password": gf_pass})
            if not r.ok:
                raise SystemExit(f"grafana API login refused: {r.status}")
            page = ctx.new_page()
            for name, uid in DASH.items():
                page.goto(f"{GRAFANA}/d/{uid}?orgId=1&kiosk&from=now-30m&to=now&refresh=",
                          wait_until="networkidle", timeout=90_000)
                time.sleep(12)  # panels render their live queries
                if "/login" in page.url:
                    raise SystemExit("grafana session lost: login page shown")
                page.screenshot(path=str(IMAGES / name))
                report["figures"][name] = {"source": f"{GRAFANA}/d/{uid} (live, kiosk)"}
            browser.close()
    finally:
        pf.terminate()

    for name in ("lab-topology.png", "grafana-fabric-telemetry.png", "agent-ui.png", "agent-ui-outcome.png"):
        p = IMAGES / name
        f = report["figures"].setdefault(name, {})
        if not p.exists():
            f["error"] = "missing"
            report["ok"] = False
            continue
        fr = subprocess.run([sys.executable, str(BASE / "check_framing.py"), str(p)], capture_output=True, text=True)
        text = ocr(p)
        f.update({"framing_rc": fr.returncode, "framing": fr.stdout.strip(),
                  "ocr_chars": len(text),
                  "operator_password_visible": op_pass in text,
                  "grafana_password_visible": gf_pass in text,
                  "credential_shaped_text": bool(CRED.search(text))})
        bad = fr.returncode != 0 or f["operator_password_visible"] or f["grafana_password_visible"] \
            or f["credential_shaped_text"]
        f["ok"] = not bad
        report["ok"] &= not bad
    print(json.dumps(report, indent=1))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
